const constant = {
  BlockName: {
    Initial: "initial",
    TyrhBlock: "tyrh",
  },
  LiquidEventType: {
    Tyrh: 0,
    Burn: 1,
    Water: 2,
    Plant: 3,
    Seed: 4,
    Holy: 5,
  },
  SproutHouseObjectId: {
    Id: 0,
    Owner: 1,
    Amount: 2,
    Yield: 3,
    Timestamp: 4,
    NftId: 5,
    Finished: 6,
  },
  SeedBankUserInfoObjectId: {
    Amount: 0,
    SeedAmount: 1,
    LifeCycle: 2,
    StartTimestamp: 3,
    LastClaimTimestamp: 4,
    NftIds: 5,
    IsStaking: 6,
  },
  PlantationTreeObjectId: {
    Id: 0,
    TypeId: 1,
    Owner: 2,
    Weight: 3,
    StepStartTimestamp: 4,
    StepEndTimestamp: 5,
    CurrentStep: 6,
    GrowthTime: 7,
    WaterAmount: 8,
    PlantAmount: 9,
    GrownUp: 10,
  },
  PlantationNftId: {
    Cattails: 0,
    Bush: 1,
    Tree: 2,
    Pine: 3,
    Plam: 4,
    Sherman: 5,
  },
  NftId: {
    TypeId: 0,
    TokenId: 1,
    Weight: 2,
    Owner: 3,
  },
  NftType: {
    YieldBoosters5: 10,
    YieldBoosters15: 11,
    YieldBoosters30: 12,
    YieldBoosters50: 13,
    YieldBoostersRandom: 14,
    SeedYieldBoosters10: 33,
    SeedYieldBoosters25: 34,
    SeedYieldBoosters50: 35,
    SeedYieldBoosters100: 36,
    SproutYieldBoosters5: 37,
    SproutYieldBoosters10: 38,
    SproutYieldBoosters15: 39,
    SproutYieldBoostersRandom: 40,
    HolyYieldBoosters10: 26,
    HolyYieldBoosters25: 27,
    HolyYieldBoosters50: 28,
    HolyYieldBoosters100: 29,
    ReduceTreeTime25: 15,
    ReduceTreeTime50: 16,
    ReduceTreeTime75: 17,
    ReduceTreeTimeRandom: 18,
    ReduceSeedTime10: 30,
    ReduceSeedTime25: 31,
    ReduceSeedTime50: 32,
    LessWater10: 19,
    LessWater25: 20,
    LessWater50: 21,
    LessWaterRandom: 22,
    Treatment10: 23,
    Treatment25: 24,
    Treatment50: 25,
    SpecialsRhWakllet: 4,
    SpecialsLiquidKing: 5,
    SpecialsMystery: 6,
    SpecialsRandom: 7,
    LeagueBoosters: 8,
    LeagueBoostersRandom: 9,
    ClaimBoosters5: 0,
    ClaimBoosters10: 1,
    ClaimBoosters15: 2,
    ClaimBoostersRandom: 3,
    WaterFountain: 41,
  },

  PointsWeight: {
    Tyrh: 5,
    StakedTyrh: 8,
    LiquidBurn: 1,
    LiquidWater: 1,
    LiquidPlant: 1,
    StakedBurn: 0.2,
    StakedPlant: 5,
    StakedWater: 5,
  },
};

export default constant;
